### ISSUE TITLE
Text input reverts to smaller size after submit

### ISSUE THREAD

**Issue by LukeGaudreau** [BCLibraries/bcbento-client#3]
[Example](https://lib-ci.bc.edu/hugo/fulltext-access/search/?any=Dew%2C+Wilcox%2C+%22generosity+and+the+maintenance+of+marital+quality%2C+%22Journal+of+marriage+and+family+75%2C+number+five+%282013%29%3A+1218%E2%80%9328%2C+https%3A%2F%2F%2Fdoi.org%2F10.1111%2FJomf.12066.q)
![20191017-112845](https://user-images.githubusercontent.com/120206/67024302-2ec56e80-f0d2-11e9-8f84-3e773742be82.png)

**Comment by Otterfan** [comment]
Resolved.
